// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: phone.proto

package com.elson.hadoop.phonebillplusprotobuf.protobuf;

public final class Phone {
  private Phone() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface pdetailOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string pnum = 1;
    /**
     * <code>required string pnum = 1;</code>
     */
    boolean hasPnum();
    /**
     * <code>required string pnum = 1;</code>
     */
    java.lang.String getPnum();
    /**
     * <code>required string pnum = 1;</code>
     */
    com.google.protobuf.ByteString
        getPnumBytes();

    // required string time = 2;
    /**
     * <code>required string time = 2;</code>
     */
    boolean hasTime();
    /**
     * <code>required string time = 2;</code>
     */
    java.lang.String getTime();
    /**
     * <code>required string time = 2;</code>
     */
    com.google.protobuf.ByteString
        getTimeBytes();

    // required string type = 3;
    /**
     * <code>required string type = 3;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 3;</code>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 3;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();
  }
  /**
   * Protobuf type {@code com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail}
   */
  public static final class pdetail extends
      com.google.protobuf.GeneratedMessage
      implements pdetailOrBuilder {
    // Use pdetail.newBuilder() to construct.
    private pdetail(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private pdetail(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final pdetail defaultInstance;
    public static pdetail getDefaultInstance() {
      return defaultInstance;
    }

    public pdetail getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private pdetail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              pnum_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              time_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              type_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.internal_static_com_elson_hadoop_phonebillplusprotobuf_protobuf_pdetail_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.internal_static_com_elson_hadoop_phonebillplusprotobuf_protobuf_pdetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail.class, com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail.Builder.class);
    }

    public static com.google.protobuf.Parser<pdetail> PARSER =
        new com.google.protobuf.AbstractParser<pdetail>() {
      public pdetail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new pdetail(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<pdetail> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string pnum = 1;
    public static final int PNUM_FIELD_NUMBER = 1;
    private java.lang.Object pnum_;
    /**
     * <code>required string pnum = 1;</code>
     */
    public boolean hasPnum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string pnum = 1;</code>
     */
    public java.lang.String getPnum() {
      java.lang.Object ref = pnum_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pnum_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string pnum = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPnumBytes() {
      java.lang.Object ref = pnum_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pnum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string time = 2;
    public static final int TIME_FIELD_NUMBER = 2;
    private java.lang.Object time_;
    /**
     * <code>required string time = 2;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string time = 2;</code>
     */
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          time_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string time = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private java.lang.Object type_;
    /**
     * <code>required string type = 3;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string type = 3;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      pnum_ = "";
      time_ = "";
      type_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPnum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPnumBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTimeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTypeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPnumBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTimeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTypeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.internal_static_com_elson_hadoop_phonebillplusprotobuf_protobuf_pdetail_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.internal_static_com_elson_hadoop_phonebillplusprotobuf_protobuf_pdetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail.class, com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail.Builder.class);
      }

      // Construct using com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        pnum_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.internal_static_com_elson_hadoop_phonebillplusprotobuf_protobuf_pdetail_descriptor;
      }

      public com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail getDefaultInstanceForType() {
        return com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail.getDefaultInstance();
      }

      public com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail build() {
        com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail buildPartial() {
        com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail result = new com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pnum_ = pnum_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail) {
          return mergeFrom((com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail other) {
        if (other == com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail.getDefaultInstance()) return this;
        if (other.hasPnum()) {
          bitField0_ |= 0x00000001;
          pnum_ = other.pnum_;
          onChanged();
        }
        if (other.hasTime()) {
          bitField0_ |= 0x00000002;
          time_ = other.time_;
          onChanged();
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000004;
          type_ = other.type_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPnum()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string pnum = 1;
      private java.lang.Object pnum_ = "";
      /**
       * <code>required string pnum = 1;</code>
       */
      public boolean hasPnum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string pnum = 1;</code>
       */
      public java.lang.String getPnum() {
        java.lang.Object ref = pnum_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          pnum_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string pnum = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPnumBytes() {
        java.lang.Object ref = pnum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pnum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string pnum = 1;</code>
       */
      public Builder setPnum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        pnum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string pnum = 1;</code>
       */
      public Builder clearPnum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pnum_ = getDefaultInstance().getPnum();
        onChanged();
        return this;
      }
      /**
       * <code>required string pnum = 1;</code>
       */
      public Builder setPnumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        pnum_ = value;
        onChanged();
        return this;
      }

      // required string time = 2;
      private java.lang.Object time_ = "";
      /**
       * <code>required string time = 2;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string time = 2;</code>
       */
      public java.lang.String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string time = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        java.lang.Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string time = 2;</code>
       */
      public Builder setTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string time = 2;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string time = 2;</code>
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }

      // required string type = 3;
      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 3;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string type = 3;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 3;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 3;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 3;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail)
    }

    static {
      defaultInstance = new pdetail(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail)
  }

  public interface pdayOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;
    /**
     * <code>repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;</code>
     */
    java.util.List<com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail> 
        getPlistList();
    /**
     * <code>repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;</code>
     */
    com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail getPlist(int index);
    /**
     * <code>repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;</code>
     */
    int getPlistCount();
    /**
     * <code>repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;</code>
     */
    java.util.List<? extends com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetailOrBuilder> 
        getPlistOrBuilderList();
    /**
     * <code>repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;</code>
     */
    com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetailOrBuilder getPlistOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.elson.hadoop.phonebillplusprotobuf.protobuf.pday}
   */
  public static final class pday extends
      com.google.protobuf.GeneratedMessage
      implements pdayOrBuilder {
    // Use pday.newBuilder() to construct.
    private pday(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private pday(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final pday defaultInstance;
    public static pday getDefaultInstance() {
      return defaultInstance;
    }

    public pday getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private pday(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                plist_ = new java.util.ArrayList<com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail>();
                mutable_bitField0_ |= 0x00000001;
              }
              plist_.add(input.readMessage(com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          plist_ = java.util.Collections.unmodifiableList(plist_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.internal_static_com_elson_hadoop_phonebillplusprotobuf_protobuf_pday_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.internal_static_com_elson_hadoop_phonebillplusprotobuf_protobuf_pday_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday.class, com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday.Builder.class);
    }

    public static com.google.protobuf.Parser<pday> PARSER =
        new com.google.protobuf.AbstractParser<pday>() {
      public pday parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new pday(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<pday> getParserForType() {
      return PARSER;
    }

    // repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;
    public static final int PLIST_FIELD_NUMBER = 1;
    private java.util.List<com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail> plist_;
    /**
     * <code>repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;</code>
     */
    public java.util.List<com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail> getPlistList() {
      return plist_;
    }
    /**
     * <code>repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;</code>
     */
    public java.util.List<? extends com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetailOrBuilder> 
        getPlistOrBuilderList() {
      return plist_;
    }
    /**
     * <code>repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;</code>
     */
    public int getPlistCount() {
      return plist_.size();
    }
    /**
     * <code>repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;</code>
     */
    public com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail getPlist(int index) {
      return plist_.get(index);
    }
    /**
     * <code>repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;</code>
     */
    public com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetailOrBuilder getPlistOrBuilder(
        int index) {
      return plist_.get(index);
    }

    private void initFields() {
      plist_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getPlistCount(); i++) {
        if (!getPlist(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < plist_.size(); i++) {
        output.writeMessage(1, plist_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < plist_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, plist_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.elson.hadoop.phonebillplusprotobuf.protobuf.pday}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.internal_static_com_elson_hadoop_phonebillplusprotobuf_protobuf_pday_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.internal_static_com_elson_hadoop_phonebillplusprotobuf_protobuf_pday_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday.class, com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday.Builder.class);
      }

      // Construct using com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPlistFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (plistBuilder_ == null) {
          plist_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          plistBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.internal_static_com_elson_hadoop_phonebillplusprotobuf_protobuf_pday_descriptor;
      }

      public com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday getDefaultInstanceForType() {
        return com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday.getDefaultInstance();
      }

      public com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday build() {
        com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday buildPartial() {
        com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday result = new com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday(this);
        int from_bitField0_ = bitField0_;
        if (plistBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            plist_ = java.util.Collections.unmodifiableList(plist_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.plist_ = plist_;
        } else {
          result.plist_ = plistBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday) {
          return mergeFrom((com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday other) {
        if (other == com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday.getDefaultInstance()) return this;
        if (plistBuilder_ == null) {
          if (!other.plist_.isEmpty()) {
            if (plist_.isEmpty()) {
              plist_ = other.plist_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePlistIsMutable();
              plist_.addAll(other.plist_);
            }
            onChanged();
          }
        } else {
          if (!other.plist_.isEmpty()) {
            if (plistBuilder_.isEmpty()) {
              plistBuilder_.dispose();
              plistBuilder_ = null;
              plist_ = other.plist_;
              bitField0_ = (bitField0_ & ~0x00000001);
              plistBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPlistFieldBuilder() : null;
            } else {
              plistBuilder_.addAllMessages(other.plist_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPlistCount(); i++) {
          if (!getPlist(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pday) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;
      private java.util.List<com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail> plist_ =
        java.util.Collections.emptyList();
      private void ensurePlistIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          plist_ = new java.util.ArrayList<com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail>(plist_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail, com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail.Builder, com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetailOrBuilder> plistBuilder_;

      /**
       * <code>repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;</code>
       */
      public java.util.List<com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail> getPlistList() {
        if (plistBuilder_ == null) {
          return java.util.Collections.unmodifiableList(plist_);
        } else {
          return plistBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;</code>
       */
      public int getPlistCount() {
        if (plistBuilder_ == null) {
          return plist_.size();
        } else {
          return plistBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;</code>
       */
      public com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail getPlist(int index) {
        if (plistBuilder_ == null) {
          return plist_.get(index);
        } else {
          return plistBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;</code>
       */
      public Builder setPlist(
          int index, com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail value) {
        if (plistBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlistIsMutable();
          plist_.set(index, value);
          onChanged();
        } else {
          plistBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;</code>
       */
      public Builder setPlist(
          int index, com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail.Builder builderForValue) {
        if (plistBuilder_ == null) {
          ensurePlistIsMutable();
          plist_.set(index, builderForValue.build());
          onChanged();
        } else {
          plistBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;</code>
       */
      public Builder addPlist(com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail value) {
        if (plistBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlistIsMutable();
          plist_.add(value);
          onChanged();
        } else {
          plistBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;</code>
       */
      public Builder addPlist(
          int index, com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail value) {
        if (plistBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlistIsMutable();
          plist_.add(index, value);
          onChanged();
        } else {
          plistBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;</code>
       */
      public Builder addPlist(
          com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail.Builder builderForValue) {
        if (plistBuilder_ == null) {
          ensurePlistIsMutable();
          plist_.add(builderForValue.build());
          onChanged();
        } else {
          plistBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;</code>
       */
      public Builder addPlist(
          int index, com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail.Builder builderForValue) {
        if (plistBuilder_ == null) {
          ensurePlistIsMutable();
          plist_.add(index, builderForValue.build());
          onChanged();
        } else {
          plistBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;</code>
       */
      public Builder addAllPlist(
          java.lang.Iterable<? extends com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail> values) {
        if (plistBuilder_ == null) {
          ensurePlistIsMutable();
          super.addAll(values, plist_);
          onChanged();
        } else {
          plistBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;</code>
       */
      public Builder clearPlist() {
        if (plistBuilder_ == null) {
          plist_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          plistBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;</code>
       */
      public Builder removePlist(int index) {
        if (plistBuilder_ == null) {
          ensurePlistIsMutable();
          plist_.remove(index);
          onChanged();
        } else {
          plistBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;</code>
       */
      public com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail.Builder getPlistBuilder(
          int index) {
        return getPlistFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;</code>
       */
      public com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetailOrBuilder getPlistOrBuilder(
          int index) {
        if (plistBuilder_ == null) {
          return plist_.get(index);  } else {
          return plistBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;</code>
       */
      public java.util.List<? extends com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetailOrBuilder> 
           getPlistOrBuilderList() {
        if (plistBuilder_ != null) {
          return plistBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(plist_);
        }
      }
      /**
       * <code>repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;</code>
       */
      public com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail.Builder addPlistBuilder() {
        return getPlistFieldBuilder().addBuilder(
            com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail.getDefaultInstance());
      }
      /**
       * <code>repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;</code>
       */
      public com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail.Builder addPlistBuilder(
          int index) {
        return getPlistFieldBuilder().addBuilder(
            index, com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail.getDefaultInstance());
      }
      /**
       * <code>repeated .com.elson.hadoop.phonebillplusprotobuf.protobuf.pdetail plist = 1;</code>
       */
      public java.util.List<com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail.Builder> 
           getPlistBuilderList() {
        return getPlistFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail, com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail.Builder, com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetailOrBuilder> 
          getPlistFieldBuilder() {
        if (plistBuilder_ == null) {
          plistBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail, com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetail.Builder, com.elson.hadoop.phonebillplusprotobuf.protobuf.Phone.pdetailOrBuilder>(
                  plist_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          plist_ = null;
        }
        return plistBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.elson.hadoop.phonebillplusprotobuf.protobuf.pday)
    }

    static {
      defaultInstance = new pday(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.elson.hadoop.phonebillplusprotobuf.protobuf.pday)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_elson_hadoop_phonebillplusprotobuf_protobuf_pdetail_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_elson_hadoop_phonebillplusprotobuf_protobuf_pdetail_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_elson_hadoop_phonebillplusprotobuf_protobuf_pday_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_elson_hadoop_phonebillplusprotobuf_protobuf_pday_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013phone.proto\022/com.elson.hadoop.phonebil" +
      "lplusprotobuf.protobuf\"3\n\007pdetail\022\014\n\004pnu" +
      "m\030\001 \002(\t\022\014\n\004time\030\002 \002(\t\022\014\n\004type\030\003 \002(\t\"O\n\004p" +
      "day\022G\n\005plist\030\001 \003(\01328.com.elson.hadoop.ph" +
      "onebillplusprotobuf.protobuf.pdetail"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_elson_hadoop_phonebillplusprotobuf_protobuf_pdetail_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_elson_hadoop_phonebillplusprotobuf_protobuf_pdetail_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_elson_hadoop_phonebillplusprotobuf_protobuf_pdetail_descriptor,
              new java.lang.String[] { "Pnum", "Time", "Type", });
          internal_static_com_elson_hadoop_phonebillplusprotobuf_protobuf_pday_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_elson_hadoop_phonebillplusprotobuf_protobuf_pday_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_elson_hadoop_phonebillplusprotobuf_protobuf_pday_descriptor,
              new java.lang.String[] { "Plist", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
