server:
  port: 8050
eureka:
  client:
    serviceUrl:
      defaultZone: http://node1:8761/eureka/
  instance:
    prefer-ip-address: true
logging:                                # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
spring:
  application:
    name: microservice-file-upload
  http:
    multipart:
      max-file-size: 2000Mb      # Max file size，默认1M
      max-request-size: 2500Mb   # Max request size，默认10M
 