f = open('somefile.txt', 'w')
f.write('First line\n')
f.write('Second line\n')
f.write('Third line\n')
f.close()
lines = list(open('somefile.txt'))
print(lines)
first, second, third = open('somefile.txt')
print(first)
print(second)
print(third)
