server:
  port: 9411
zipkin:
  collector:
    rabbitmq:
      addresses: node4:5672
      password: mq
      username: mq
      queue: zipkin
  storage:
    type: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      hosts: http://node4:9200
      index: zipkin
      index-shards: 5
      index-replicas: 1