spring:
  application:
    name: microservice-discovery-eureka-ha

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://node1:8761/eureka/,http://node2:8762/eureka/
---
spring:
  profiles: node1
server:
  port: 8761
eureka:
  instance:
    hostname: node1
---
spring:
  profiles: node2
server:
  port: 8762
eureka:
  instance:
    hostname: node2