error:
  whitelabel:
    enabled: false

amazon:
  associate_id: habuma-20

logging:
  config: classpath:logging-config.xml
  level:
    root: INFO

endpoints:
  jmx:
    domain: readinglist
    uniqueNames: true
  beans:
    sensitive: true
  shutdown:
    enabled: true

info:
  contact:
    email: hotenglish@163.com
    phone: 13138654828

management:
  context-path: /mgmt
  health:
    mongo:
      enabled: true
