server:
  port: 8088
spring:
  application:
    name: microservice-consumer-movie
eureka:
  client:
    serviceUrl:
      defaultZone: http://node1:8761/eureka/
  instance:
    prefer-ip-address: true