server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: node4
    port: 5672
    username: mq
    password: mq
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG